version: "3.4"

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

  # postgres:
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak
  #     POSTGRES_PASSWORD: password

  # keycloak:
  #   image: quay.io/keycloak/keycloak
  #   command:
  #     - start-dev
  #     - --import-realm
  #   volumes:
  #     - ./backend/ZwooInfoDashboard/realm-export.json:/opt/keycloak/data/import/realm.json
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #   ports:
  #     - 9080:8080
  #   depends_on:
  #     - postgres

  docs:
    image: artireg.igd20.de/zwoo/docs:latest
    volumes:
      - ./docs-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8002:8002

  mails:
    image: maildev/maildev
    ports:
      - 9587:9587
      - 9090:9090
    environment:
      - MAILDEV_WEB_PORT=9090
      - MAILDEV_SMTP_PORT=9587
      - MAILDEV_INCOMING_USER=local
      - MAILDEV_INCOMING_PASS=admin

volumes:
  db-data:
  zwoo-encryption-keys:
  postgres_data:
    driver: local
