version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - conan_remote=
        - conan_user=
        - conan_password=
    port:
      - 8000:8000
    environment:
      # SMTP Settings
      - SMTP_HOST_URL=""
      - SMTP_HOST_PORT=""
      - SMTP_HOST_EMAIL=""
      - SMTP_USERNAME=""
      - SMTP_PASSWORD=""
      # Database Settings
      - ZWOO_DATABASE_CONNECTION_STRING="mongodb://127.0.0.1:27019"
      # Backend Config
      - ZWOO_RECAPTCHA_SIDESECRET=""
      # SSL Settings
      - USE_SSL="False"
      # Only used when USE_SSL = False
      - SSL_PEM=""
      - SSL_CERTIFICATE=""
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - db-data:/data/db
volumes:
  db-data:
