version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ZWOO_USERNAME=""
      - ZWOO_EMAIL=""
      - ZWOO_PASSWORD=""
      - ZWOO_SIDESECRET=""
      - ZWOO_PORT=8000
      - ZWOO_DOMAIN=0.0.0.0
      - MONGO_CONN_STR='mongodb://127.0.0.1:27019'
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - db-data:/data/db
volumes:
  db-data:
