#ifndef _ZRPCODES_H_
#define _ZRPCODES_H_

enum e_Roles
{
    HOST = 1,
    PLAYER = 2,
    SPECTATOR = 3
};

enum e_ZRPOpCodes
{
    // General
    PLAYER_JOINED = 100,
    SPECTATOR_JOINED = 101,
    PLAYER_LEFT = 102,
    SPECTATOR_LEFT = 103,
    SEND_MESSAGE = 104,
    RECEIVE_MESSAGE = 105,
    PLAYER_LEAVE = 106,
    GET_ALL_PLAYERS_IN_LOBBY = 108,
    ALL_PLAYERS_IN_LOBBY = 109,
    SPECTATOR_TO_PLAYER = 110,
    PLAYER_TO_SPECTATOR = 111,
    PLAYER_TO_HOST = 112,
    YOU_ARE_HOST_NOW = 113,
    NEW_HOST = 114,
    KICK_PLAYER = 115,
    PLAYER_CHANGED_ROLE = 116,

    // Lobby
    CHANGE_SETTINGS = 200,
    SETTINGS_CHANGED = 201,
    GET_ALL_SETTINGS = 202,
    ALL_SETTINGS = 203,
    START_GAME = 210,

    // Game
    GAME_STARTED = 300,
    START_TURN = 301,
    END_TURN = 302,
    REQUEST_END_TURN = 303, // irrelevant for beta
    PLACE_CARD = 304,
    DRAW_CARD = 305,
    GET_CARD = 306,
    REMOVE_CARD = 307,
    STATE_UPDATE = 308,
    GET_HAND = 310,
    SEND_HAND = 311,
    GET_PLAYER_CARD_AMOUNT = 312,
    SEND_PLAYER_CARD_AMOUNT = 313,
    GET_STACK_TOP = 314,
    SEND_STACK_TOP = 315,
    GET_PLAYER_DECISION = 316,
    SEND_PLAYER_DECISION = 317,
    GAME_WON = 399,
};

#endif
