import _Checkbox from './Checkbox.vue';
import _Form from './Form.vue';
import _FormActions from './FormActions.vue';
import _FormAlternativeAction from './FormAlternativeAction.vue';
import _FormError from './FormError.vue';
import _FormRow from './FormRow.vue';
import _FormSecondaryAction from './FormSecondaryAction.vue';
import _FormSubmit from './FormSubmit.vue';
import _FormTitle from './FormTitle.vue';
import _TextInput from './TextInput.vue';

export const Form = _Form;
export const FormTitle = _FormTitle;
export const FormRow = _FormRow;
export const TextInput = _TextInput;
export const Checkbox = _Checkbox;
export const FormError = _FormError;
export const FormActions = _FormActions;
export const FormSubmit = _FormSubmit;
export const FormSecondaryAction = _FormSecondaryAction;
export const FormAlternativeAction = _FormAlternativeAction;
