<script lang="ts" setup>
/**
 * Local Search Box implementation compatible with vitepress search index
 *
 * This is a component used to search through the documentation and API.
 * It uses a local search index generated by vitepress. All links link
 * directly to the site in the vitepress docs served on the same domain.
 *
 * This implementation is derived from the original VPLocalSearchBox.vue
 * https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPLocalSearchBox.vue
 * MIT License | Copyright (c) 2019-present, Yuxi (Evan) You
 */

import { computedAsync, debouncedWatch, onKeyStroke, useEventListener, useScrollLock } from '@vueuse/core';
import { useFocusTrap } from '@vueuse/integrations/useFocusTrap';
import MiniSearch, { type SearchResult } from 'minisearch';
import { computed, markRaw, nextTick, onBeforeUnmount, onMounted, type Ref, ref, shallowRef, toRefs, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { LRUCache } from '@/core/helper/lru';
import ZwooIcon from '@/modules/zwoo-icons/ZwooIcon.vue';

export type DocsMode = 'docs' | 'api' | 'dev';
type Result = {
  title: string;
  titles: string[];
  text?: string;
};

const props = defineProps<{
  defaultMode: DocsMode;
  urlPrefix: Record<DocsMode, string>;
  indexUris: Record<DocsMode, string>;
}>();

const { t } = useI18n();
const cache = new LRUCache<string, Map<string, string>>(16); // 16 files
const { defaultMode, urlPrefix, indexUris } = toRefs(props);

const emit = defineEmits<{
  (e: 'close'): void;
}>();

const currentMode = ref(defaultMode.value); // current search mode
const isHelpOpen = ref(false); // whether the keyboard shortcuts help is open
const filterText = ref(''); // user inputted search query
const enableNoResults = ref(false); // whether to show no results message
const results: Ref<(SearchResult & Result)[]> = shallowRef([]); // current search results
const selectedIndex = ref(-1); // selected index indicator for keyboard navigation
const disableMouseOver = ref(false); // whether to disable mouse over selection for keyboard navigation

const searchIndexDataUrl = computed(() => indexUris.value[currentMode.value]); // url to the current search index
const disableReset = computed(() => {
  return filterText.value?.length <= 0;
});

const el = shallowRef<HTMLElement>(); // the search box element
const resultsEl = shallowRef<HTMLElement>(); // the list of results
const searchInput = ref<HTMLInputElement>();

const isLocked = useScrollLock(document.body); // whether the body scroll is locked
const { activate } = useFocusTrap(el, {
  immediate: true,
  allowOutsideClick: true,
  clickOutsideDeactivates: true,
  escapeDeactivates: true
});

// the current search index
const searchIndex = computedAsync(async () =>
  markRaw(
    MiniSearch.loadJSON<Result>((await import(/* @vite-ignore */ searchIndexDataUrl.value))?.default, {
      fields: ['title', 'titles', 'text'],
      storeFields: ['title', 'titles'],
      searchOptions: {
        fuzzy: 0.2,
        prefix: true,
        boost: { title: 4, text: 2, titles: 1 }
      }
    })
  )
);

watch(filterText, () => {
  enableNoResults.value = false;
});

// update the results as the suer types
debouncedWatch(
  () => [searchIndex.value, filterText.value] as const,
  async ([index, filterTextValue], old, onCleanup) => {
    if (old?.[0] !== index) {
      // in case of hmr
      cache.clear();
    }

    let canceled = false;
    onCleanup(() => {
      canceled = true;
    });

    if (!index) return;

    // Search
    results.value = index.search(filterTextValue).slice(0, 16) as (SearchResult & Result)[];
    enableNoResults.value = true;

    results.value = results.value.map(r => {
      const [id, anchor] = r.id.split('#');
      const map = cache.get(id);
      const text = map?.get(anchor) ?? '';
      return { ...r, text };
    });

    await nextTick();
    if (canceled) return;
    // FIXME: without this whole page scrolls to the bottom
    if (resultsEl.value?.firstElementChild?.scrollIntoView) {
      resultsEl.value.firstElementChild.scrollIntoView({ block: 'start' });
    }
  },
  { debounce: 200, immediate: true }
);

watch(results, r => {
  selectedIndex.value = r.length ? 0 : -1;
  scrollToSelectedResult();
});

onMounted(() => {
  focusSearchInput();
  window.history.pushState(null, '', null);
  nextTick(() => {
    isLocked.value = true;
    nextTick().then(() => activate());
  });
});

onBeforeUnmount(() => {
  isLocked.value = false;
});

function resetSearch() {
  filterText.value = '';
  nextTick().then(() => focusSearchInput(false));
}

function openDocs() {
  window.location.href = urlPrefix.value['docs'];
}

function focusSearchInput(select = true) {
  searchInput.value?.focus();
  select && searchInput.value?.select();
}

function onSearchBarClick(event: PointerEvent) {
  if (event.pointerType === 'mouse') {
    focusSearchInput();
  }
}

function scrollToSelectedResult() {
  nextTick(() => {
    const selectedEl = document.querySelector('.result.selected');
    if (selectedEl) {
      selectedEl.scrollIntoView({
        block: 'nearest'
      });
    }
  });
}

onKeyStroke('ArrowUp', event => {
  event.preventDefault();
  selectedIndex.value--;
  if (selectedIndex.value < 0) {
    selectedIndex.value = results.value.length - 1;
  }
  disableMouseOver.value = true;
  scrollToSelectedResult();
});

onKeyStroke('ArrowDown', event => {
  event.preventDefault();
  selectedIndex.value++;
  if (selectedIndex.value >= results.value.length) {
    selectedIndex.value = 0;
  }
  disableMouseOver.value = true;
  scrollToSelectedResult();
});

onKeyStroke('Enter', e => {
  if (e.isComposing) return;

  if (e.target instanceof HTMLButtonElement && e.target.type !== 'submit') return;

  const selectedPackage = results.value[selectedIndex.value];
  if (e.target instanceof HTMLInputElement && !selectedPackage) {
    e.preventDefault();
    return;
  }

  if (selectedPackage) {
    const targetUrl = urlPrefix.value[currentMode.value] + selectedPackage.id;
    window.open(`/redirect?t=${targetUrl}`, '_blank');
    emit('close');
  }
});

onKeyStroke('Escape', () => {
  emit('close');
});

useEventListener('popstate', event => {
  event.preventDefault();
  emit('close');
});
</script>

<template>
  <div
    ref="el"
    role="button"
    :aria-owns="results?.length ? 'search-list' : undefined"
    aria-expanded="true"
    aria-haspopup="listbox"
    aria-labelledby="search-label"
    class="ZwooSearchBox"
    @click.stop=""
  >
    <div class="shell">
      <form class="search-bar" @pointerup="onSearchBarClick($event)" @submit.prevent="">
        <label :title="t('zwooUi.search.buttonText')" id="search-label" for="search-input">
          <span aria-hidden="true" class="search-icon local-search-icon">
            <ZwooIcon icon="akar-icons:search" />
          </span>
        </label>
        <input
          ref="searchInput"
          v-model="filterText"
          :placeholder="t('zwooUi.search.buttonText')"
          id="search-input"
          aria-labelledby="search-label"
          class="search-input"
          @keyup.stop=""
        />
        <div class="search-actions">
          <button class="clear-button" type="reset" :disabled="disableReset" :title="t('zwooUi.search.resetButtonTitle')" @click="resetSearch">
            <span class="local-search-icon">
              <ZwooIcon icon="akar-icons:backspace" />
            </span>
          </button>

          <button class="open-button" type="button" :title="t('zwooUi.search.openDocs')" @click="openDocs">
            <span class="local-search-icon">
              <ZwooIcon icon="akar-icons:link-out" />
            </span>
          </button>

          <button class="close-button" :title="t('zwooUi.search.closeButtonTitle')" @click="emit('close')">
            <span class="local-search-icon">
              <ZwooIcon icon="akar-icons:cross" />
            </span>
          </button>
        </div>
      </form>

      <ul
        ref="resultsEl"
        :id="results?.length ? 'search-list' : undefined"
        :role="results?.length ? 'listbox' : undefined"
        :aria-labelledby="results?.length ? 'search-label' : undefined"
        class="results"
        @mousemove="disableMouseOver = false"
      >
        <li v-for="(p, index) in results" :key="p.id" role="option" :aria-selected="selectedIndex === index ? 'true' : 'false'">
          <a
            :href="`/redirect?t=${urlPrefix[currentMode] + p.id}`"
            target="_black"
            class="result"
            :class="{
              selected: selectedIndex === index
            }"
            :aria-label="[...p.titles, p.title].join(' > ')"
            @mouseenter="!disableMouseOver && (selectedIndex = index)"
            @focusin="selectedIndex = index"
            @click="$emit('close')"
          >
            <div>
              <div class="titles">
                <span class="title-icon">#</span>
                <span v-for="(t, index) in p.titles" :key="index" class="title">
                  <span class="text" v-html="t" />
                  <span class="local-search-icon">
                    <ZwooIcon icon="iconoir:nav-arrow-right" />
                  </span>
                </span>
                <span class="title main">
                  <span class="text" v-html="p.title" />
                </span>
              </div>
            </div>
          </a>
        </li>
        <li v-if="filterText && !results.length && enableNoResults" class="no-results">
          {{ t('zwooUi.search.noResultsText') }} "<strong>{{ filterText }}</strong
          >"
        </li>
        <li v-if="!filterText" class="motivation">
          <span class="motivation-icon">
            <ZwooIcon icon="mdi:sheep" />
          </span>
          <span class="greeting">
            {{ t('zwooUi.search.motivationGreeting') }}
          </span>
          <span class="info">
            {{ t('zwooUi.search.motivationText') }}
          </span>
        </li>
      </ul>

      <div class="search-footer">
        <div v-if="!isHelpOpen" class="search-mode">
          <button
            class="mode-button docs"
            :class="{ active: currentMode === 'docs' }"
            :title="t('zwooUi.search.mode.docs')"
            @click="currentMode = 'docs'"
          >
            {{ t('zwooUi.search.mode.docs') }}</button
          ><button
            class="mode-button dev"
            :class="{ active: currentMode === 'dev' }"
            :title="t('zwooUi.search.mode.dev')"
            @click="currentMode = 'dev'"
          >
            {{ t('zwooUi.search.mode.dev') }}</button
          ><button
            class="mode-button api"
            :class="{ active: currentMode === 'api' }"
            :title="t('zwooUi.search.mode.api')"
            @click="currentMode = 'api'"
          >
            {{ t('zwooUi.search.mode.api') }}
          </button>
        </div>
        <div v-else class="search-keyboard-shortcuts">
          <span>
            <kbd :aria-label="t('zwooUi.search.footer.navigateUpKeyAriaLabel')">
              <span class="navigate-icon">
                <ZwooIcon icon="iconoir:arrow-up" />
              </span>
            </kbd>
            <kbd :aria-label="t('zwooUi.search.footer.navigateDownKeyAriaLabel')">
              <span class="navigate-icon">
                <ZwooIcon icon="iconoir:arrow-down" />
              </span>
            </kbd>
            {{ t('zwooUi.search.footer.navigateText') }}
          </span>
          <span>
            <kbd :aria-label="t('zwooUi.search.footer.selectKeyAriaLabel')">
              <span class="navigate-icon">
                <ZwooIcon icon="iconoir:long-arrow-down-left" />
              </span>
            </kbd>
            {{ t('zwooUi.search.footer.selectText') }}
          </span>
          <span>
            <kbd :aria-label="t('zwooUi.search.footer.closeKeyAriaLabel')">esc</kbd>
            {{ t('zwooUi.search.footer.closeText') }}
          </span>
        </div>
        <button class="help-button" :title="t('zwooUi.search.footer.helpButtonTitle')" @click="isHelpOpen = !isHelpOpen">
          <span class="local-search-icon">
            <ZwooIcon icon="akar-icons:circle-x" v-if="isHelpOpen" />
            <ZwooIcon icon="akar-icons:question" v-else />
          </span>
        </button>
      </div>
    </div>
  </div>
  <div @click="emit('close')" class="click-outside"></div>
</template>

<style scoped>
.ZwooSearchBox {
  position: fixed;
  z-index: 1000;
  bottom: 1rem;
  right: 1rem;
  display: flex;
  color: var(--color-text-hex);
}

.click-outside {
  position: fixed;
  inset: 0;
  z-index: 999;
}

.shell {
  position: relative;
  padding: 0.75rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  background: var(--color-surface-hex);
  width: min(calc(100vw - 2rem), 600px);
  height: min(80vh, 500px);
  border-radius: 0.5rem;
  border: 1px solid var(--color-border-hex);
}

.search-bar {
  border: 1px solid var(--color-border-hex);
  border-radius: 0.25rem;
  display: flex;
  align-items: center;
  padding: 0 0.75rem;
  cursor: text;
}

.search-bar:focus-within {
  border-color: var(--color-primary-hex);
}

.local-search-icon {
  display: block;
  font-size: 18px;
}

.navigate-icon {
  display: block;
  font-size: 10px;
}

.search-icon {
  margin: 0.5rem;
}

@media (max-width: 767px) {
  .search-icon {
    display: none;
  }
}

.search-input {
  padding: 0.4rem 0.75rem;
  font-size: inherit;
  width: 100%;
  background-color: transparent;
  outline: none;
}

@media (max-width: 767px) {
  .search-input {
    padding: 0.4rem 0.2rem;
  }
}

.search-actions {
  display: flex;
  gap: 0.2rem;
}

.help-button,
.search-actions button {
  padding: 0.5rem;
}

.help-button:hover,
.search-actions button:not([disabled]):hover {
  color: var(--color-primary-text-hex);
}

.search-actions button.clear-button:disabled {
  opacity: 0.6;
}

.search-footer {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
}

.mode-button {
  padding: 0.4rem 0.75rem;
  border: none;
  background-color: var(--color-bg-hex);
  cursor: pointer;
  border-radius: 0.25rem;
  margin-right: 0.5rem;
  transition:
    background-color var(--duration-xs) ease-in-out,
    border-color var(--duration-xs) ease-in-out,
    scale var(--duration-xs) ease-in-out;
}

.mode-button:active {
  scale: 0.95;
}

.mode-button.active {
  background-color: var(--color-primary-hex);
  color: var(--color-primary-contrast-text-hex);
}

.search-keyboard-shortcuts {
  font-size: 0.8rem;
  opacity: 75%;
  display: flex;
  flex-wrap: wrap;
  gap: 0.25rem 1rem;
  line-height: 14px;
  align-items: flex-end;
  height: 2.3rem;
}

.search-keyboard-shortcuts span {
  display: flex;
  align-items: center;
  gap: 0.25rem;
}

@media (max-width: 767px) {
  .search-keyboard-shortcuts {
    display: none;
  }
  .help-button {
    display: none;
  }
}

.help-button {
  margin-right: -0.5rem;
  margin-bottom: -0.5rem;
}

.search-keyboard-shortcuts kbd {
  background: rgba(128, 128, 128, 0.1);
  border-radius: 4px;
  padding: 3px 6px;
  min-width: 20px;
  display: inline-block;
  text-align: center;
  vertical-align: middle;
  border: 1px solid rgba(128, 128, 128, 0.15);
  box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.1);
}

.results {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  overflow-x: hidden;
  overflow-y: auto;
  overscroll-behavior: contain;
  flex: 1;
  padding: 0.5rem;
  height: 100%;
  background-color: var(--color-bg-hex);
  border-radius: 0.5rem;
}

.result {
  display: flex;
  align-items: center;
  gap: 8px;
  border-radius: 4px;
  transition: none;
  line-height: 1rem;
  border: solid 2px var(--color-border-light-hex);
  outline: none;
}

.result > div {
  margin: 0.75rem;
  width: 100%;
  overflow: hidden;
}

@media (max-width: 767px) {
  .result > div {
    margin: 0.5rem;
  }
}

.titles {
  display: flex;
  flex-wrap: wrap;
  gap: 0.25rem;
  position: relative;
  z-index: 1001;
  padding: 2px 0;
  align-items: center;
}

.title {
  display: flex;
  align-items: center;
  gap: 4px;
}

.title.main {
  font-weight: 600;
}

.title-icon {
  opacity: 0.7;
  font-weight: 600;
  color: var(--color-primary-text);
}

.title svg {
  opacity: 0.6;
}

.result.selected {
  border-color: var(--color-border-divider-hex);
  background-color: var(--color-bg-hover-hex);
}

.result.selected .excerpt {
  opacity: 1;
}

.result.selected .titles,
.result.selected .title-icon {
  color: var(--color-primary-text-hex) !important;
}

.no-results {
  font-size: 0.9rem;
  text-align: center;
  padding: 1rem;
  height: 100%;
  background-color: var(--color-bg-hex);
  border-radius: 0.5rem;
}

.motivation {
  height: 100%;
  background-color: var(--color-bg-hex);
  border-radius: 0.5rem;
  padding: 1rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  text-align: center;
}

.motivation .greeting {
  font-size: 1.2rem;
  font-weight: 600;
}

.motivation .info {
  font-size: 0.8rem;
}

.motivation-icon {
  font-size: 4rem;
  animation: sheepAnimation 3s linear infinite;
}

svg {
  flex: none;
}

@keyframes sheepAnimation {
  0% {
    transform: rotate(0deg);
  }
  5% {
    transform: rotate(-15deg);
  }
  10% {
    transform: rotate(-5deg);
  }
  15% {
    transform: rotate(-10deg);
  }
  20% {
    transform: rotate(0deg);
  }
}
</style>
