version: "3.4"

services:
  db:
    image: mongo:4.4.16-focal
    ports:
      - 27017:27017

  frontend:
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - backend
      - docs
    ports:
      - 8080:80

  backend:
    build: ../backend
    depends_on:
      - testdata
    ports:
      - 8000:80
    environment:
      # SMTP Settings
      - ZWOO__EMAIL__USESSL=True
      - ZWOO__EMAIL__PORT=1
      - ZWOO__EMAIL__HOST=x
      - ZWOO__EMAIL__USERNAME=x
      - ZWOO__EMAIL__PASSWORD=x
      - ZWOO__EMAIL__EMAIL=info@igd20.de
      - ZWOO__EMAIL__CONTACTEMAIL=info@igd20.de
      # Database Settings
      - ZWOO__DATABASE__CONNECTIONURI=mongodb://db:27017
      - ZWOO__DATABASE__DBNAME=zwoo
      # Backend Config
      - ZWOO__FEATURES__CAPTCHASECRET=0x0000000000000000000000000000000000000000
      # SSL Settings
      - ZWOO__SERVER__USESSL=False
      - ZWOO__SERVER__CORS=https://zwoo.igd20.de
      - ZWOO__SERVER__DOMAIN=zwoo.igd20.de
      - ZWOO__SERVER__COOKIEDOMAIN=zwoo.igd20.de
      - ZWOO__FEATURES__BETA=True

  testdata:
    build: ./testdata
    depends_on:
      - db
    command: sh /app/import.sh
    healthcheck:
      test: ["CMD", "true"]

  docs:
    build:
      context: ./docs
      dockerfile: ./Dockerfile
    ports:
      - 80:80

  # e2e-test:
  #   image: xy
  #   command: run-tests.sh
