version: '3.4'

services:
  db:
    image: mongo:4.4.16-focal
    ports:
      - 27017:27017

  frontend:
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - 8080:80

  backend:
    build: ../backend
    depends_on:
      - testdata
    ports:
      - 8000:80
    environment:
      # SMTP Settings
      - SMTP_HOST_URL=x
      - SMTP_HOST_PORT=1
      - SMTP_HOST_EMAIL=x
      - SMTP_USERNAME=x
      - SMTP_PASSWORD=x
      # Database Settings
      - ZWOO_DATABASE_CONNECTION_STRING=mongodb://db:27017
      - ZWOO_DATABASE_NAME=zwoo
      # Backend Config
      - ZWOO_RECAPTCHA_SIDESECRET=xxx
      # SSL Settings
      - USE_SSL=False
      - ZWOO_CORS=https://zwoo.igd20.de
      - ZWOO_DOMAIN=zwoo.igd20.de
      - ZWOO_ENCRYPTION_KEY=x
      - ZWOO_USE_LOGRUSH=False
      - ZWOO_LOGRUSH_URL=http://host.docker.internal:7000
      - ZWOO_LOGRUSH_ALIAS=Zwoo
      - ZWOO_LOGRUSH_ID=x
      - ZWOO_LOGRUSH_KEY=x
      - ZWOO_BETA=True
  
  testdata:
    build: ./testdata
    depends_on:
      - db
    command: sh /app/import.sh

  # e2e-test:
  #   image: xy
  #   command: run-tests.sh