
name: Frontend Pipeline
on:
  workflow_call:
  push:
    paths-ignore:
      - "backend/**"
  pull_request:
    paths-ignore:
      - "backend/**"
    

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Setup
        working-directory: ./frontend
        run: 'yarn'
      - name: Lint
        working-directory: ./frontend
        run: 'yarn lint:ci'
      - name: Dependency Check
        working-directory: ./frontend
        run: 'yarn deps:check'
      - name: Check i18n
        working-directory: ./frontend
        run: 'yarn i18n:check'
      - name: Format
        working-directory: ./frontend
        run: 'yarn format:ci'
      - name: Test
        working-directory: ./frontend
        run: 'yarn test:unit'
      - name: Build
        working-directory: ./frontend
        run: 'yarn build'