name: Backend Pipeline

on:
  workflow_call:
  push:
    paths-ignore:
      - "frontend/**"
  pull_request:
    paths-ignore:
      - "frontend/**"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: zwoo-hq/setup-zwooc@v1
        with:
          version: 1.0.0-alpha.2
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: Install dependencies
        working-directory: ./backend
        run: |
          dotnet restore "./Zwoo.Backend/Zwoo.Backend.csproj"
          dotnet workload restore
      - name: Build
        working-directory: ./backend
        run: zwooc build -o server
      # - name: Test
      #   working-directory: ./backend
      #   run: dotnet test "./Zwoo.GameEngine/Zwoo.GameEngine.csproj" -c Release --verbosity normal

  ziad:
    runs-on: ubuntu-latest
    steps:
      - uses: zwoo-hq/setup-zwooc@v1
        with:
          version: 1.0.0-alpha.2
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: Install dependencies
        working-directory: ./backend
        run: |
          dotnet restore "./Zwoo.Dashboard/Zwoo.Dashboard.csproj"
          dotnet workload restore
      - name: Build
        working-directory: ./backend
        run: zwooc build -o ziad

  wasm-gamelogic:
    runs-on: ubuntu-latest
    steps:
      - uses: zwoo-hq/setup-zwooc@v1
        with:
          version: 1.0.0-alpha.2
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: Install dependencies
        working-directory: ./backend
        run: |
          dotnet restore "./Zwoo.GameEngine.Wasm/Zwoo.GameEngine.Wasm.csproj"
          dotnet workload restore
      - name: Build
        working-directory: ./backend
        run: zwooc build -o wasm

  local-server:
    runs-on: ubuntu-latest
    steps:
      - uses: zwoo-hq/setup-zwooc@v1
        with:
          version: 1.0.0-alpha.2
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: Install dependencies
        working-directory: ./backend
        run: |
          dotnet restore "./Zwoo.Backend.LocalServer/Zwoo.Backend.LocalServer.csproj"
          dotnet workload restore
      - name: Build
        working-directory: ./backend
        run: zwooc build -o local
