name: Backend Pipeline

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths-ignore:
      - "frontend/**"
  pull_request:
    paths-ignore:
      - "frontend/**"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: zwoo-hq/setup-zwooc@v1
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: Install dependencies
        working-directory: ./backend
        run: |
          dotnet workload restore
          dotnet restore "./Zwoo.Backend/Zwoo.Backend.csproj"
      - name: Build
        working-directory: ./backend
        run: zwooc build server
      - name: Test
        working-directory: ./backend
        run: dotnet test Zwoo.GameEngine.Tests --verbosity normal

  ziad:
    runs-on: ubuntu-latest
    steps:
      - uses: zwoo-hq/setup-zwooc@v1
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: Install dependencies
        working-directory: ./backend
        run: |
          dotnet workload restore
          dotnet restore "./Zwoo.Dashboard/Zwoo.Dashboard.csproj"
      - name: Build
        working-directory: ./backend
        run: zwooc build ziad

  wasm-gamelogic:
    runs-on: ubuntu-latest
    steps:
      - uses: zwoo-hq/setup-zwooc@v1
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: Install dependencies
        working-directory: ./backend
        run: |
          dotnet workload restore
          dotnet restore "./Zwoo.GameEngine.Wasm/Zwoo.GameEngine.Wasm.csproj"
      - name: Build
        working-directory: ./backend
        run: zwooc build wasm

  local-server:
    runs-on: ubuntu-latest
    steps:
      - uses: zwoo-hq/setup-zwooc@v1
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      - name: Install dependencies
        working-directory: ./backend
        run: |
          dotnet workload restore
          dotnet restore "./Zwoo.Backend.LocalServer/Zwoo.Backend.LocalServer.csproj"
      - name: Build
        working-directory: ./backend
        run: zwooc build -e local-server local
