name: Backend Pipeline

on:
  workflow_call:
  push:
    paths-ignore:
      - "frontend/**"
  pull_request:
    paths-ignore:
      - "frontend/**"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8"
      - name: Install dependencies
        working-directory: ./backend
        run: dotnet restore "./Zwoo.Backend/Zwoo.Backend.csproj"
      - name: Build
        working-directory: ./backend
        run: dotnet build "./Zwoo.Backend/Zwoo.Backend.csproj" -c Release --no-restore
      # - name: Test
      #   working-directory: ./backend
      #   run: dotnet test "./Zwoo.GameEngine/Zwoo.GameEngine.csproj" -c Release --no-restore --verbosity normal

  ziad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8"
      - name: Install dependencies
        working-directory: ./backend
        run: dotnet restore "./Zwoo.Dashboard/Zwoo.Dashboard.csproj"
      - name: Build
        working-directory: ./backend
        run: dotnet build "./Zwoo.Dashboard/Zwoo.Dashboard.csproj" -c Release --no-restore

  wasm-Zwoo.GameEngine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8"
      - name: Install workloads
        working-directory: ./backend
        run: dotnet workload restore
      - name: Install dependencies
        working-directory: ./backend
        run: dotnet restore "./Zwoo.GameEngine.Wasm/Zwoo.GameEngine.Wasm.csproj"
      - name: Build
        working-directory: ./backend
        run: dotnet publish -c Release -p:RunAOTCompilation=true "./Zwoo.GameEngine.Wasm/Zwoo.GameEngine.Wasm.csproj"
