name: Backend Docker Pipeline

"on":
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  backend-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Backend Image
        run: "docker build . -f ./backend/Dockerfile --build-arg version_override=$(git rev-parse HEAD) -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend/backend:nightly"
      - name: Log into JFrog
        run: "docker login ${{ secrets.DOCKER_REPO_URL }} -p ${{ secrets.DOCKER_REPO_PASS }} -u ${{ secrets.DOCKER_REPO_USER }}"
      - name: Push Image
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend/backend:nightly"

  backend-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Admin Dashboard Image
        run: "docker build . -f ./backend/DockerfileDashboard -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-dashboard/admin-info-dashboard:nightly"
      - name: Log into JFrog
        run: "docker login ${{ secrets.DOCKER_REPO_URL }} -p ${{ secrets.DOCKER_REPO_PASS }} -u ${{ secrets.DOCKER_REPO_USER }}"
      - name: Push Image
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-dashboard/admin-info-dashboard:nightly"
