name: Docker Dev Instance Pipeline

"on":
  workflow_dispatch:

jobs:
  frontend-docker-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build frontend image
        run: "docker build -f ./frontend/Dockerfile --build-arg version_override=$(git rev-parse HEAD) --build-arg profile=dev-instance -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend:dev ."
      - name: Login to gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPO_URL}}
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_PASS }}
      - name: Push image
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend:dev"

  backend-docker-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        run: "docker build . -f ./backend/Dockerfile --build-arg version_override=$(git rev-parse HEAD) -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend:dev"
      - name: Login to gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPO_URL}}
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_PASS }}
      - name: Push image
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend:dev"

  backend-dashboard-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ZIAD image
        run: "docker build . -f ./backend/DockerfileDashboard -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-dashboard:dev"
      - name: Login to gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPO_URL}}
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_PASS }}
      - name: Push image
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-dashboard:dev"
