name: Frontend Docker Pipeline

"on":
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  frontend-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: "docker build -f ./frontend/Dockerfile --build-arg version_override=$(git rev-parse HEAD) -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend:nightly ."
      - name: Login to gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPO_URL}}
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_PASS }}
      - name: Push image
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend/frontend:nightly"
