name: Docker Dev Instance Pipeline

"on":
  workflow_dispatch:

jobs:
  frontend-docker-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: "docker build -f ./frontend/Dockerfile --build-arg version_override=$(git rev-parse HEAD) --build-arg build_command=build-fe-only:dev-instance -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend/frontend:dev ."
      - name: Log into JFrog
        run: "docker login ${{ secrets.DOCKER_REPO_URL }} -p ${{ secrets.DOCKER_REPO_PASS }} -u ${{ secrets.DOCKER_REPO_USER }}"
      - name: Push Image
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend/frontend:dev"

  backend-docker-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Backend Image
        working-directory: ./backend
        run: "docker build . -f ./Dockerfile --build-arg version_override=$(git rev-parse HEAD) -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend/backend:dev"
      - name: Log into JFrog
        run: "docker login ${{ secrets.DOCKER_REPO_URL }} -p ${{ secrets.DOCKER_REPO_PASS }} -u ${{ secrets.DOCKER_REPO_USER }}"
      - name: Push Image
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend/backend:dev"

  backend-dashboard-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Admin Dashboard Image
        working-directory: ./backend
        run: "docker build . -f ./DockerfileDashboard -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-dashboard/admin-info-dashboard:dev"
      - name: Log into JFrog
        run: "docker login ${{ secrets.DOCKER_REPO_URL }} -p ${{ secrets.DOCKER_REPO_PASS }} -u ${{ secrets.DOCKER_REPO_USER }}"
      - name: Push Image
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-dashboard/admin-info-dashboard:dev"
