name: Zwoo Release Pipeline

on:
  push:
    tags:
      - "**"

jobs:
  frontend-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get release version
        run: |
          echo "$GITHUB_REF"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build frontend image
        run: "docker build -f ./frontend/Dockerfile -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend:latest -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend:${{ env.RELEASE_VERSION }} ."
      - name: Login to gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPO_URL}}
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_PASS }}
      - name: Push image (version latest)
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend:latest"
      - name: Push image (actual version)
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend:${{ env.RELEASE_VERSION }}"

  backend-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get release version
        run: |
          echo "$GITHUB_REF"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build backend image
        run: "docker build . -f ./backend/Dockerfile -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend:latest  -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend:${{ env.RELEASE_VERSION }}"
      - name: Login to gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPO_URL}}
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_PASS }}
      - name: Push image (version latest)
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend:latest"
      - name: Push image (actual version)
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend:${{ env.RELEASE_VERSION }}"

  dashboard-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get release version
        run: |
          echo "$GITHUB_REF"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build ZIAD image
        run: "docker build . -f ./backend/DockerfileDashboard -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-dashboard:latest  -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-dashboard:${{ env.RELEASE_VERSION }}"
      - name: Login to gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPO_URL}}
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_PASS }}
      - name: Push image (version latest)
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-dashboard:latest"
      - name: Push image (actual version)
        run: "docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-dashboard:${{ env.RELEASE_VERSION }}"
