
name: Zwoo Release Pipeline

on:
  push:
    tags:        
      - '**'  

jobs:
  frontend-release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Build Image
          working-directory: ./frontend
          run: 'docker build . -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend/frontend:latest -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend/frontend:${{ github.ref }}'
        - name: Log into JFrog
          run: 'docker login ${{ secrets.DOCKER_REPO_URL }} -p ${{ secrets.DOCKER_REPO_PASS }} -u ${{ secrets.DOCKER_REPO_USER }}'
        - name: Push Image (version latest)
          run: 'docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend/frontend:latest'
        - name: Push Image (actual version)
          run: 'docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-frontend/frontend:${{ github.ref }}'

  backend-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Backend Image
        working-directory: ./backend
        run: 'docker build . -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend/backend:latest  -t ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend/backend:${{ github.ref }}'
      - name: Log into JFrog
        run: 'docker login ${{ secrets.DOCKER_REPO_URL }} -p ${{ secrets.DOCKER_REPO_PASS }} -u ${{ secrets.DOCKER_REPO_USER }}'
      - name: Push Image (version latest)
        run: 'docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend/backend:latest'
      - name: Push Image (actual version)
        run: 'docker push ${{ secrets.DOCKER_REPO_URL }}/zwoo-backend/backend:${{ github.ref }}'