
name: E2E-Test Pipeline
on:
  workflow_dispatch:
  # todo remove on push to every thing and add pr
  push:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Test Runner Image
        run:  docker build -f ./e2e/Dockerfile -t zwoo-e2e .
      - name: Prepare Container
        run: docker run -d --privileged --name test-runner zwoo-e2e
      - name: Run E2E-Tests
        run: docker exec -i test-runner /app/e2e/run-tests.sh
