name: Release Tauri

on:
  push:
    tags:        
      - '**'

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Install dotnet wasm-tools
      run: dotnet workload install wasm-tools
    - name: install app dependencies and build it
      working-directory: ./frontend
      run: yarn && yarn build:tauri
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        projectPath: ./frontend
        configPath: ./frontend/src-tauri/tauri.conf.json
        tagName: ${{ github.ref }} # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: Release ${{ github.ref }}
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: true